build:
  environment:
    php: '7.0.8'
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=coverage.xml'
        coverage:
          file: 'coverage.xml'
          format: 'php-clover'

checks:
  php:
    code_rating: true
    duplication: true